---
git:
  # SNU
  - https://github.com/Shougo/neosnippet-snippets
  - https://github.com/fatih/vim-go
  - https://github.com/honza/vim-snippets

  # LSP
  - https://github.com/Ikuyadeu/vscode-R
  - https://github.com/Rocketseat/rocketseat-vscode-react-native-snippets
  - https://github.com/dsznajder/vscode-es7-javascript-react-snippets
  - https://github.com/johnpapa/vscode-angular-snippets
  - https://github.com/rafamadriz/friendly-snippets
  - https://github.com/sdras/vue-vscode-snippets
  - https://github.com/snipsnapdev/snipsnap
  - https://github.com/xabikos/vscode-javascript
  - https://github.com/xabikos/vscode-react

paths:
  lsp:
    - friendly-snippets/snippets
    - rocketseat-vscode-react-native-snippets/snippets
    - snipsnap/snippets
    - vscode-R/snippets
    - vscode-angular-snippets/snippets
    - vscode-es7-javascript-react-snippets/src/snippets
    - vscode-javascript/snippets
    - vscode-react/snippets
    - vue-vscode-snippets/snippets
  neosnippet:
    - neosnippet-snippets/neosnippets
    - vim-go/gosnippets/snippets
    - vim-snippets/snippets
  ultisnip:
    - vim-go/gosnippets/UltiSnips
    - vim-snippets/UltiSnips

remaps:
  dart:
    - dart-flutter
    - flutter
  django:
    - djangohtml
  dotenv:
    - dotenv-safe
  vue:
    - javascript
    - vue-pug
    - vue-script
    - vue-script-router
    - vue-script-vuex
    - vue-template
    - vuex
